version: "3.6"

services:
  db:
    image: "postgres"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - ./config/.env

  web:
    <<: &web
      build:
        context: .
        dockerfile: ./docker/Dockerfile
        args:
          DJANGO_ENV: development
      volumes:
        - .:/code
        - django-static:/var/www/django/static
      depends_on:
        - db
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db
    command: python -Wd manage.py runserver 0.0.0.0:8080

volumes:
  pgdata:
  django-static:
  django-media: